name: fehu_app
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg_provider: ^1.0.3
  get: ^4.6.1
  shared_preferences: ^2.0.13
  dropdown_search: ^2.0.0
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  linkwell: ^2.0.6
  auto_direction: ^0.0.5
  shimmer: ^2.0.0
  url_launcher: ^6.1.3
  syncfusion_flutter_pdfviewer: ^20.1.60-beta

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.10
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/locales/
    - assets/

  fonts:
    - family: Noor
      fonts:
        - asset: assets/fonts/noor.ttf
    - family: Poppin
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
