// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO28z5FkHab7CR_HUBFK8MhDW4m1BSXdQ',
    appId: '1:1092854168522:web:b36f65adb24be44d376d33',
    messagingSenderId: '1092854168522',
    projectId: 'fehu-3de79',
    authDomain: 'fehu-3de79.firebaseapp.com',
    storageBucket: 'fehu-3de79.appspot.com',
    measurementId: 'G-4HP9048TJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDODKLsq981ChsnpHp955AfGthBsMmBC8',
    appId: '1:1092854168522:android:b4562cd2ef96634d376d33',
    messagingSenderId: '1092854168522',
    projectId: 'fehu-3de79',
    storageBucket: 'fehu-3de79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBK0_XKmoR_X0M9Sv0oUUTNe0BWtSKOyY',
    appId: '1:1092854168522:ios:d95ac9814afba97f376d33',
    messagingSenderId: '1092854168522',
    projectId: 'fehu-3de79',
    storageBucket: 'fehu-3de79.appspot.com',
    iosClientId: '1092854168522-sacfcsc0ndrj5k39ookv5jlbej0tfed0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fehuApp',
  );
}
